#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=5

# Production URL is a public value and useful to code later (metadataBase,
# Playwright BASE_URL), so it lands in .env.local rather than .env.
ENV_FILE=".env.local"

REPO="n8v-max/agent-dash"

banner "agent-dash → Vercel"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Sign in to Vercel with GitHub"
say "Hobby (free) tier is all this project needs."
open_url "https://vercel.com/login"
step "Choose 'Continue with GitHub' and authorise as n8v-max."
note "Already signed in? Nothing to do — just carry on."
pause "Signed in?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Import $REPO"
say "This creates the Vercel project and wires up the Git integration."
open_url "https://vercel.com/new"
step "Under 'Import Git Repository', find agent-dash and click 'Import'."
note "Not listed? Click 'Adjust GitHub App Permissions' and grant access to"
note "agent-dash. You must be the repo Owner — a Collaborator cannot import."
step "Framework Preset should auto-detect 'Next.js'. Leave Root Directory as ./"
step "Leave Build and Output Settings untouched — the defaults are correct."
note "pnpm is detected from pnpm-lock.yaml; no install command override needed."
step "Click 'Deploy' and wait for the build to finish."
pause "Build finished?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Confirm the build environment"
say "Two things to eyeball, both already pinned in the repo."
step "Open the deployment's 'Building' log. The first Next.js line should read:"
note "    ▲ Next.js 16.3.4 (Turbopack)"
warn "If it does NOT say (Turbopack), stop and tell me — ticket 14 requires it."
step "Now open Settings → Build and Deployment → Node.js Version."
note "It should read 24.x. package.json engines.node ('24.x') overrides this"
note "setting anyway, so a mismatch here is cosmetic — but 24.x is the default."
if confirm "Did the build log say (Turbopack)?"; then
  say "Good — ticket 14's bundler constraint is satisfied on the deployed build."
else
  SKIPPED+=("Build did not report Turbopack — investigate before building UI")
  warn "recorded as outstanding; see the summary at the end"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Capture and smoke-test the production URL"
step "Go to the project Overview and copy the production domain."
note "It looks like agent-dash.vercel.app or agent-dash-<hash>.vercel.app"
ask NEXT_PUBLIC_SITE_URL "Paste the production URL (with https://):"
write_env NEXT_PUBLIC_SITE_URL "$NEXT_PUBLIC_SITE_URL"

say ""
say "Checking it responds..."
if code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$NEXT_PUBLIC_SITE_URL"); then
  if [[ "$code" == "200" ]]; then
    printf '  %s✓ %s returned 200%s\n' "$GREEN" "$NEXT_PUBLIC_SITE_URL" "$RESET"
  elif [[ "$code" == "401" ]]; then
    warn "$NEXT_PUBLIC_SITE_URL returned 401 — Deployment Protection is on."
    note "Settings → Deployment Protection → set Vercel Authentication to"
    note "'Standard Protection' off, or the grader cannot open the URL."
    SKIPPED+=("Turn off Vercel Authentication so the deployment is public")
  else
    warn "$NEXT_PUBLIC_SITE_URL returned $code — expected 200."
    SKIPPED+=("Production URL returned $code; check the deployment")
  fi
else
  warn "could not reach $NEXT_PUBLIC_SITE_URL at all"
  SKIPPED+=("Production URL unreachable; check the deployment")
fi

say ""
note "Git integration is now automatic: pushes to main deploy to production,"
note "and every pull request gets its own preview URL, commented on the PR."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Set the session signing key on Vercel"
say "The app signs its session JWT with AUTH_JWT_SECRET (R-T14). Dev and CI carry"
say "their own keys; production needs one that exists only in the Vercel dashboard."

PROD_JWT_SECRET=$(openssl rand -base64 32)
say ""
say "Here is a fresh 32-byte key for production:"
printf '  %s%s%s\n' "$BOLD" "$PROD_JWT_SECRET" "$RESET"
note "Not written to any file here — copy it straight into Vercel and nowhere else."
open_url "https://vercel.com/dashboard"
step "Open the agent-dash project, then Settings → Environment Variables."
step "Add the key AUTH_JWT_SECRET with the value above."
step "Tick Production. Tick Preview too if you want preview URLs to sign in."
step "Save, then Deployments → latest → ⋯ → Redeploy."
note "Env vars are read at build and at runtime, so the deployment already live"
note "will not pick this up until it is redeployed."
warn "Without it, sign-in fails on the deployed build — the app throws at boot."
if confirm "Added AUTH_JWT_SECRET and redeployed?"; then
  say "Good — sign-in will work on the deployed build."
else
  SKIPPED+=("Set AUTH_JWT_SECRET in the Vercel dashboard and redeploy, or sign-in fails")
  warn "recorded as outstanding; see the summary at the end"
fi

# The local dev key is a different key. Only generate one if .env.local has
# none, so re-running this wizard never invalidates a working dev session.
if ! _existing AUTH_JWT_SECRET >/dev/null 2>&1; then
  write_env AUTH_JWT_SECRET "$(openssl rand -base64 32)"
  note "also wrote a separate local dev key to $ENV_FILE"
fi

# The library's summary short-circuits under `set -e` when no GitHub secrets
# were written — this wizard writes none, so relax errexit for the summary.
set +e
finish
